import { FieldReport } from '../../types';

export const mockFieldReports: FieldReport[] = [
  {
    id: '1',
    title: 'Nắp cống hỏng gây nguy hiểm',
    description: 'Nắp cống bị hỏng gây mất an toàn cho người đi đường',
    address: 'Khu đất Dịch vụ 25,2ha vân canh, Hoài Đức',
    category: 'security',
    status: 'pending',
    imageUrl: 'https://picsum.photos/seed/1/300/200',
    createdAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    timeAgo: '1 phút trước',
    likes: 5,
    comments: 2,
  },
  {
    id: '2',
    title: 'Cống tắc khu đất dịch vụ',
    description: 'Đường 24m khu đất dịch vụ bị lại y...',
    address: 'Đường 24m khu đất dịch vụ, Hoài Đức',
    category: 'environment',
    status: 'processing',
    imageUrl: 'https://picsum.photos/seed/2/300/200',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    timeAgo: '3 phút trước',
    likes: 12,
    comments: 4,
  },
  {
    id: '3',
    title: 'Đề nghị UBND xã Thanh Oai cần xử lý rút điểm bãi rác đã...',
    description: 'Khu vực chiến chiện, sát đường...',
    address: 'Khu vực chiến chiện, xã Thanh Oai',
    category: 'environment',
    status: 'pending',
    imageUrl: 'https://picsum.photos/seed/3/300/200',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    timeAgo: '5 phút trước',
    likes: 34,
    comments: 10,
  },
  {
    id: '4',
    title: 'Khu homestay Sunrise BaVi không có phòng hát karaoke c...',
    description: 'Homstay Sunrise Bavi, số 06 thô...',
    address: 'Số 06 thôn ..., xã Ba Vì',
    category: 'civilization',
    status: 'done',
    imageUrl: 'https://picsum.photos/seed/4/300/200',
    createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    timeAgo: '6 phút trước',
    likes: 7,
    comments: 1,
  },
  {
    id: '5',
    title: 'Nhậu nhét mở loa đến 24h gây mất trật tự',
    description: 'Số 1 BT1 bắc linh đàm, Phường H...',
    address: 'Số 1 BT1 Bắc Linh Đàm, Phường Hoàng Liệt',
    category: 'security',
    status: 'pending',
    imageUrl: 'https://picsum.photos/seed/5/300/200',
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    timeAgo: '7 phút trước',
    likes: 89,
    comments: 23,
  },
  {
    id: '6',
    title: 'Liên tục lấn chiếm lòng đường sau nhiều lần phản ánh',
    description: 'Số nhà 68 đường dx4, kđt đặng...',
    address: 'Số nhà 68 đường DX4, Khu đô thị Đặng Xá',
    category: 'construction',
    status: 'processing',
    imageUrl: 'https://picsum.photos/seed/6/300/200',
    createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    timeAgo: '9 phút trước',
    likes: 45,
    comments: 18,
  },
  {
    id: '7',
    title: 'Đường hỏng gây ngập úng sau mưa lớn',
    description: 'Tuyến đường bị hỏng nặng gây ngập úng',
    address: 'Phố Huế, Hai Bà Trưng, Hà Nội',
    category: 'traffic',
    status: 'done',
    imageUrl: 'https://picsum.photos/seed/7/300/200',
    createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    timeAgo: '20 phút trước',
    likes: 120,
    comments: 35,
  },
  {
    id: '8',
    title: 'Rác thải tràn lan tại khu dân cư',
    description: 'Rác không được thu gom nhiều ngày',
    address: 'Ngõ 123 Xuân Thủy, Cầu Giấy',
    category: 'environment',
    status: 'rejected',
    imageUrl: 'https://picsum.photos/seed/8/300/200',
    createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    timeAgo: '35 phút trước',
    likes: 56,
    comments: 12,
  },
];
