import { AdminProcedureReport } from '../../types';

export const mockAdminReports: AdminProcedureReport[] = [
  {
    id: '1',
    title: 'Chậm trả giấy phép lái xe',
    reporterName: 'TRẦN BÁ HỢI',
    status: 'done',
    createdAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    timeAgo: '11 phút trước',
  },
  {
    id: '2',
    title: 'Đã xong thủ  cấp gplx mà chưa nhận được',
    reporterName: 'Trần Trung Kiên',
    status: 'done',
    createdAt: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
    timeAgo: '14 phút trước',
  },
  {
    id: '3',
    title: 'Thủ tục hành chính phức tạp khi đổi mới',
    reporterName: 'LÊ THỊ MINH QUÝ',
    status: 'done',
    createdAt: new Date(Date.now() - 26 * 60 * 1000).toISOString(),
    timeAgo: '26 phút trước',
  },
  {
    id: '4',
    title: 'Tổ dân phố ra cv thu tiền có đúng không ?',
    reporterName: 'Đoàn Hoàng Kim',
    status: 'done',
    createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    timeAgo: '1 giờ trước',
  },
  {
    id: '5',
    title: 'GIẢI QUYẾT KHÔNG ĐÚNG QUY ĐỊNH, THIẾU MINH BẠCH',
    reporterName: 'Nguyễn Tài Linh',
    status: 'done',
    createdAt: new Date(Date.now() - 65 * 60 * 1000).toISOString(),
    timeAgo: '1 giờ trước',
  },
  {
    id: '6',
    title: 'Khó khăn khi làm đăng ký thường trú',
    reporterName: 'Bùi Phương Anh',
    status: 'done',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    timeAgo: '2 giờ trước',
  },
  {
    id: '7',
    title: 'Đất nhà tôi chưa được nhận tiền',
    reporterName: 'Nguyễn Văn Thành',
    status: 'done',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    timeAgo: '3 giờ trước',
  },
  {
    id: '8',
    title: 'Thất lạc hồ sơ, chậm giải quyết hồ sơ làm sổ đỏ',
    reporterName: 'Lê Văn Hùng',
    status: 'processing',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    timeAgo: '4 giờ trước',
  },
  {
    id: '9',
    title: 'Chứng thực giấy tờ bị trả lại nhiều lần',
    reporterName: 'Phạm Thị Mai',
    status: 'pending',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    timeAgo: '5 giờ trước',
  },
];
