import { AdminProcedureReport } from '../../types';

export const mockAdminReports: AdminProcedureReport[] = [
  {
    id: '1',
    title: 'Hồ sơ đề nghị hỗ trợ kinh phí sửa chữa nhà Đại đoàn kết cho hộ cận nghèo',
    reporterName: 'Trần Văn Tiến (Thôn Chiến Chiện)',
    status: 'done',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    timeAgo: '25 phút trước',
  },
  {
    id: '2',
    title: 'Thủ tục đăng ký thành lập Tổ tự quản Bảo vệ Môi trường và Thu gom rác thải xóm 3',
    reporterName: 'Nguyễn Thị Loan (Thôn Cao Dương)',
    status: 'done',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    timeAgo: '45 phút trước',
  },
  {
    id: '3',
    title: 'Hồ sơ xác nhận hoàn cảnh khó khăn để xin miễn giảm học phí cho con em hội viên phụ nữ',
    reporterName: 'Lê Thị Thu (Thôn Bình Minh)',
    status: 'done',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    timeAgo: '2 giờ trước',
  },
  {
    id: '4',
    title: 'Thủ tục đề nghị vay vốn Quỹ Quốc gia giải quyết việc làm qua kênh Hội Cựu chiến binh',
    reporterName: 'Đỗ Văn Cường (Thôn Tam Hưng)',
    status: 'processing',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    timeAgo: '3 giờ trước',
  },
  {
    id: '5',
    title: 'Kiến nghị rút ngắn thời gian cấp Giấy chứng nhận quyền sử dụng đất nông nghiệp dồn điền đổi thửa',
    reporterName: 'Phạm Văn Hùng (Thôn Cự Khê)',
    status: 'processing',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    timeAgo: '5 giờ trước',
  },
  {
    id: '6',
    title: 'Đăng ký công nhận danh hiệu "Gia đình Văn hóa tiêu biểu 3 năm liên tục"',
    reporterName: 'Bùi Thị Lan (Thôn Bích Hòa)',
    status: 'done',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    timeAgo: '6 giờ trước',
  },
  {
    id: '7',
    title: 'Thủ tục chuyển sinh hoạt Đoàn và giới thiệu Đoàn viên ưu tú kết nạp Đảng',
    reporterName: 'Lê Hoàng Nam (Bí thư Chi đoàn)',
    status: 'done',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    timeAgo: '8 giờ trước',
  },
  {
    id: '8',
    title: 'Hồ sơ đề nghị hỗ trợ đột xuất do thiên tai úng ngập mùa mưa bão',
    reporterName: 'Nguyễn Văn Đạt (Thôn Mỹ Hưng)',
    status: 'pending',
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    timeAgo: '10 giờ trước',
  },
];
