import { DistrictReport, ReportStats } from '../../types';

export const mockStats: ReportStats = {
  pending: 12,
  processing: 18,
  done: 286,
  rejected: 4,
};

export const mockDistrictReports: DistrictReport[] = [
  {
    id: '1',
    name: 'Thôn Chiến Chiện (Trung tâm)',
    total: 58,
    overdue: 0,
    pending: 2,
    processing: 4,
    done: 52,
    rejected: 0,
    dissatisfied: 1,
    veryDissatisfied: 0,
  },
  {
    id: '2',
    name: 'Thôn Thanh Cao',
    total: 44,
    overdue: 1,
    pending: 1,
    processing: 3,
    done: 39,
    rejected: 1,
    dissatisfied: 2,
    veryDissatisfied: 0,
  },
  {
    id: '3',
    name: 'Thôn Cao Dương',
    total: 49,
    overdue: 0,
    pending: 2,
    processing: 2,
    done: 45,
    rejected: 0,
    dissatisfied: 1,
    veryDissatisfied: 0,
  },
  {
    id: '4',
    name: 'Thôn Bình Minh',
    total: 38,
    overdue: 0,
    pending: 1,
    processing: 3,
    done: 34,
    rejected: 0,
    dissatisfied: 0,
    veryDissatisfied: 0,
  },
  {
    id: '5',
    name: 'Thôn Tam Hưng',
    total: 36,
    overdue: 1,
    pending: 2,
    processing: 2,
    done: 31,
    rejected: 1,
    dissatisfied: 1,
    veryDissatisfied: 1,
  },
  {
    id: '6',
    name: 'Thôn Cự Khê',
    total: 32,
    overdue: 0,
    pending: 1,
    processing: 2,
    done: 29,
    rejected: 0,
    dissatisfied: 0,
    veryDissatisfied: 0,
  },
  {
    id: '7',
    name: 'Thôn Bích Hòa (Làng nghề)',
    total: 41,
    overdue: 0,
    pending: 2,
    processing: 1,
    done: 37,
    rejected: 1,
    dissatisfied: 1,
    veryDissatisfied: 0,
  },
  {
    id: '8',
    name: 'Thôn Mỹ Hưng',
    total: 22,
    overdue: 0,
    pending: 1,
    processing: 1,
    done: 20,
    rejected: 0,
    dissatisfied: 0,
    veryDissatisfied: 0,
  },
];
