import { DistrictReport, ReportStats } from '../../types';

export const mockStats: ReportStats = {
  pending: 2721,
  processing: 1960,
  done: 88060,
  rejected: 28232,
};

export const mockDistrictReports: DistrictReport[] = [
  {
    id: '1',
    name: 'Phường Chương Mỹ',
    total: 805,
    overdue: 86,
    pending: 51,
    processing: 97,
    done: 535,
    rejected: 121,
    dissatisfied: 27,
    veryDissatisfied: 55,
  },
  {
    id: '2',
    name: 'Phường Vĩnh Hưng',
    total: 1088,
    overdue: 65,
    pending: 19,
    processing: 74,
    done: 849,
    rejected: 146,
    dissatisfied: 49,
    veryDissatisfied: 100,
  },
  {
    id: '3',
    name: 'Phường Hồng Hà',
    total: 1794,
    overdue: 38,
    pending: 42,
    processing: 88,
    done: 1520,
    rejected: 144,
    dissatisfied: 32,
    veryDissatisfied: 68,
  },
  {
    id: '4',
    name: 'Phường Hoàng Liệt',
    total: 2134,
    overdue: 52,
    pending: 78,
    processing: 112,
    done: 1800,
    rejected: 144,
    dissatisfied: 41,
    veryDissatisfied: 88,
  },
  {
    id: '5',
    name: 'Xã Thanh Oai',
    total: 634,
    overdue: 21,
    pending: 23,
    processing: 45,
    done: 520,
    rejected: 46,
    dissatisfied: 18,
    veryDissatisfied: 31,
  },
  {
    id: '6',
    name: 'Phường Cầu Giấy',
    total: 987,
    overdue: 44,
    pending: 31,
    processing: 62,
    done: 820,
    rejected: 74,
    dissatisfied: 23,
    veryDissatisfied: 47,
  },
];
