import { FieldReport } from '../../types';

export const mockFieldReports: (FieldReport & { targetOrganization?: string })[] = [
  {
    id: '1',
    title: 'Giám sát tiến độ và chất lượng thi công tuyến đường liên thôn từ Thôn 1 sang Thôn 2',
    description: 'Đề nghị Ban Giám sát Đầu tư Cộng đồng xã kiểm tra độ dày lớp bê tông và việc đặt cống thoát nước tại đoạn Km 1+200, hiện tại khi mưa lớn nước tràn vào ruộng lúa của bà con.',
    address: 'Đoạn Km 1+200 tuyến đường liên thôn, Thôn 2, Xã Thanh Oai',
    category: 'supervision',
    targetOrganization: 'mttq',
    status: 'done',
    departmentAssigned: 'Ban Giám sát Đầu tư Cộng đồng - Ủy ban MTTQ Xã',
    imageUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb180c5f5?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    timeAgo: '15 phút trước',
    likes: 56,
    comments: 12,
    satisfactionRating: 5,
    reporterName: 'Trần Anh',
    ubndResponse: {
      officerName: 'Đồng chí Nguyễn Văn Minh (Chủ tịch Ủy ban MTTQ Xã)',
      department: 'Ban Thường trực Ủy ban MTTQ Việt Nam Xã',
      officialContent: 'Ban Giám sát Đầu tư Cộng đồng đã chủ trì làm việc với Ban QLDA và đơn vị thi công, thống nhất bổ sung 02 cửa cống tiêu thoát nước D600 tại vị trí phản ánh. Đơn vị thi công đã hoàn thành lắp đặt ngày 17/08/2026.',
      documentNumber: 'Số 48/TB-MTTQ',
      responseDate: '17/08/2026 16:30',
      resultImageUrl: 'https://images.unsplash.com/photo-1590486803833-1c5dc8ddd4c8?w=600&h=400&fit=crop',
    },
  },
  {
    id: '2',
    title: 'Công khai danh sách và tiến độ giải ngân Quỹ "Vì người nghèo" xây nhà Đại đoàn kết',
    description: 'Kính đề nghị Thường trực Mặt trận Xã thông tin cụ thể về 15 hộ gia đình khó khăn được bình xét hỗ trợ xây sửa nhà Đại đoàn kết đợt 2 năm 2026 để xóm làng cùng chung tay giúp đỡ ngày công.',
    address: 'Thôn Chiến Chiện, Xã Thanh Oai, Hà Nội',
    category: 'welfare',
    targetOrganization: 'mttq',
    status: 'done',
    departmentAssigned: 'Ban Vận động Quỹ Vì người nghèo - Ủy ban MTTQ Xã',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    timeAgo: '45 phút trước',
    likes: 88,
    comments: 15,
    satisfactionRating: 5,
    reporterName: 'Trần Anh',
    ubndResponse: {
      officerName: 'Đồng chí Nguyễn Văn Minh (Chủ tịch Ủy ban MTTQ Xã)',
      department: 'Ủy ban Mặt trận Tổ quốc Việt Nam Xã Thanh Oai',
      officialContent: 'Ủy ban MTTQ Xã đã công khai danh sách 15 hộ nghèo, cận nghèo được phê duyệt hỗ trợ xây nhà Đại đoàn kết (mỗi căn 50.000.000 đồng) trên Cổng thông tin điện tử và hệ thống loa truyền thanh xã.',
      documentNumber: 'Số 52/TB-MTTQ',
      responseDate: '16/08/2026 10:15',
      resultImageUrl: 'https://images.unsplash.com/photo-1593113598332-cd288d649433?w=600&h=400&fit=crop',
    },
  },
  {
    id: '3',
    title: 'Đề nghị Đoàn Thanh niên hỗ trợ cài đặt định danh điện tử VNeID mức 2 cho người cao tuổi',
    description: 'Nhiều cụ ông cụ bà tại Thôn Cao Dương sử dụng điện thoại thông minh chưa quen và đi lại khó khăn, đề nghị Đoàn Thanh niên xã cử tổ tình nguyện viên đến tận nhà hỗ trợ kích hoạt.',
    address: 'Cụm 3, Thôn Cao Dương, Xã Thanh Oai',
    category: 'youth_field',
    targetOrganization: 'youth',
    status: 'processing',
    departmentAssigned: 'Đoàn TNCS Hồ Chí Minh Xã (Khối MTTQ)',
    imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    timeAgo: '2 giờ trước',
    likes: 112,
    comments: 24,
    reporterName: 'Trần Anh',
    ubndResponse: {
      officerName: 'Đồng chí Lê Hoàng Nam (Bí thư Đoàn Thanh niên Xã)',
      department: 'BTV Đoàn TNCS Hồ Chí Minh Xã Thanh Oai',
      officialContent: 'Đoàn Xã đã ban hành Kế hoạch số 21/KH-ĐTN, phân công 20 đoàn viên phối hợp Công an xã trực tiếp đến các hộ gia đình có người cao tuổi vào Thứ Bảy & Chủ Nhật tuần này.',
      documentNumber: 'Số 21/KH-ĐTN',
      responseDate: '17/08/2026 14:00',
    },
  },
  {
    id: '4',
    title: 'Hội Phụ nữ nhân rộng mô hình "Gia đình 5 không, 3 sạch" và phân loại rác hữu cơ tại nguồn',
    description: 'Khu vực Xóm 4 Thôn Bình Minh có nhu cầu tham gia tập huấn ủ phân hữu cơ vi sinh từ phụ phẩm nông nghiệp và rác thải nhà bếp. Kính đề nghị Hội Phụ nữ xã tổ chức hướng dẫn.',
    address: 'Xóm 4, Thôn Bình Minh, Xã Thanh Oai, Hà Nội',
    category: 'women_field',
    targetOrganization: 'women',
    status: 'done',
    departmentAssigned: 'Hội Liên hiệp Phụ nữ Xã (Khối MTTQ)',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    timeAgo: '4 giờ trước',
    likes: 64,
    comments: 9,
    satisfactionRating: 5,
    reporterName: 'Lê Thị Thu Thủy',
    ubndResponse: {
      officerName: 'Đồng chí Phạm Thị Mai (Chủ tịch Hội LHPN Xã)',
      department: 'Hội Liên hiệp Phụ nữ Xã Thanh Oai',
      officialContent: 'Hội Phụ nữ xã đã phối hợp với Trung tâm Khuyến nông tổ chức lớp chuyển giao kỹ thuật phân loại rác và trao tặng 50 thùng ủ vi sinh cho các chi hội.',
      documentNumber: 'Số 16/BC-PN',
      responseDate: '15/08/2026 11:00',
      resultImageUrl: 'https://images.unsplash.com/photo-1618477461853-cf6ed80faba5?w=600&h=400&fit=crop',
    },
  },
  {
    id: '5',
    title: 'Tổ Tuần tra Cựu chiến binh duy trì trật tự an ninh và nhắc nhở tiếng ồn đêm khuya',
    description: 'Tại khu vực giáp ranh cụm xóm 2 Thôn Tam Hưng có tình trạng thanh thiếu niên tụ tập rú ga xe máy và hát karaoke loa kéo quá 23h00 gây ảnh hưởng giấc ngủ của người già và trẻ nhỏ.',
    address: 'Khu vực Ngã ba giáp ranh Thôn Tam Hưng, Xã Thanh Oai',
    category: 'veterans_field',
    targetOrganization: 'veterans',
    status: 'done',
    departmentAssigned: 'Hội Cựu chiến binh Xã (Khối MTTQ)',
    imageUrl: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    timeAgo: '5 giờ trước',
    likes: 95,
    comments: 21,
    satisfactionRating: 5,
    reporterName: 'Nguyễn Văn Đạt',
    ubndResponse: {
      officerName: 'Đồng chí Trần Văn Hùng (Chủ tịch Hội CCB Xã)',
      department: 'Hội Cựu chiến binh Xã Thanh Oai',
      officialContent: 'Tổ Tự quản ANTT Hội CCB đã phối hợp cùng Công an xã tổ chức tuần tra khép kín từ 21h00 - 24h00, ký cam kết không vi phạm với 04 hộ gia đình và giải tán nhóm thanh niên tụ tập.',
      documentNumber: 'Số 09/TB-CCB',
      responseDate: '17/08/2026 08:30',
    },
  },
  {
    id: '6',
    title: 'Hội Nông dân hỗ trợ hướng dẫn thủ tục vay vốn ưu đãi NHCSXH đầu tư máy móc nông nghiệp',
    description: 'Tổ hợp tác sản xuất lúa chất lượng cao Thôn Cự Khê có nhu cầu tiếp cận nguồn vốn Quỹ Hỗ trợ Nông dân và Ngân hàng Chính sách Xã hội để cơ giới hóa nông nghiệp vụ Thu Đông.',
    address: 'Hợp tác xã Nông nghiệp Thôn Cự Khê, Xã Thanh Oai',
    category: 'farmer_field',
    targetOrganization: 'farmers',
    status: 'processing',
    departmentAssigned: 'Hội Nông dân Xã (Khối MTTQ)',
    imageUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    timeAgo: '6 giờ trước',
    likes: 73,
    comments: 16,
    reporterName: 'Đặng Đình Tuấn',
    ubndResponse: {
      officerName: 'Đồng chí Nguyễn Văn Nông (Chủ tịch Hội Nông dân Xã)',
      department: 'BCH Hội Nông dân Xã Thanh Oai',
      officialContent: 'Hội Nông dân Xã đã tiếp nhận hồ sơ vay vốn của Tổ hợp tác, hoàn thiện hồ sơ dự án vay 500 triệu đồng từ Quỹ Hỗ trợ Nông dân nguồn Trung ương và dự kiến giải ngân vào ngày 25/08/2026.',
      documentNumber: 'Số 28/TB-HND',
      responseDate: '18/08/2026 09:00',
    },
  },
  {
    id: '7',
    title: 'Công đoàn xã tư vấn bảo vệ quyền lợi hợp đồng lao động và an toàn vệ sinh lao động tại làng nghề',
    description: 'Đề nghị Công đoàn cơ quan phối hợp kiểm tra công tác trang bị bảo hộ lao động và ký kết hợp đồng cho công nhân may mặc tại Cụm tiểu thủ công nghiệp làng nghề Bích Hòa.',
    address: 'Cụm công nghiệp làng nghề Bích Hòa, Xã Thanh Oai',
    category: 'union_field',
    targetOrganization: 'union',
    status: 'done',
    departmentAssigned: 'Công đoàn Cơ quan Xã (Khối MTTQ)',
    imageUrl: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=600&h=400&fit=crop',
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    timeAgo: '8 giờ trước',
    likes: 51,
    comments: 11,
    satisfactionRating: 5,
    reporterName: 'Nguyễn Thị Hằng',
    ubndResponse: {
      officerName: 'Đồng chí Hoàng Văn Công (Chủ tịch Công đoàn Xã)',
      department: 'Công đoàn Cơ quan Xã Thanh Oai',
      officialContent: 'Công đoàn Xã đã tổ chức buổi đối thoại giữa chủ cơ sở sản xuất và 85 người lao động, các cơ sở đã đồng thuận tăng mức phụ cấp độc hại và trang bị đầy đủ bảo hộ lao động.',
      documentNumber: 'Số 14/TB-CĐX',
      responseDate: '16/08/2026 15:45',
    },
  },
];
