import { FieldReport } from '../../types';

export const mockFieldReports: (FieldReport & { targetOrganization?: string })[] = [
  {
    id: '1',
    title: 'Công khai danh sách 15 hộ nghèo hỗ trợ nhà Đại đoàn kết 2026',
    description: 'Đề nghị Ủy ban MTTQ Xã công khai danh sách và tiêu chí bình xét các hộ được hỗ trợ kinh phí xây dựng nhà Đại đoàn kết năm 2026.',
    address: 'Thôn 2, xã Thanh Oai, Hà Nội',
    category: 'welfare',
    targetOrganization: 'mttq',
    status: 'done',
    departmentAssigned: 'Ban Thường trực Ủy ban MTTQ Việt Nam Xã',
    imageUrl: 'https://picsum.photos/seed/1/300/200',
    createdAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    timeAgo: '1 phút trước',
    likes: 42,
    comments: 8,
    satisfactionRating: 5,
    ubndResponse: {
      officerName: 'Đồng chí Nguyễn Văn Minh (Chủ tịch Ủy ban MTTQ Xã)',
      department: 'Ủy ban Mặt trận Tổ quốc Việt Nam Xã',
      officialContent: 'Ủy ban MTTQ Xã đã công khai minh bạch toàn bộ 15 hộ nghèo được hỗ trợ nhà Đại đoàn kết trên bảng tin và ứng dụng.',
      documentNumber: 'Số 45/TB-MTTQ',
      responseDate: '24/07/2026 14:30',
      resultImageUrl: 'https://picsum.photos/seed/30/300/200',
    },
  },
  {
    id: '2',
    title: 'Kiến nghị Đoàn Thanh niên hỗ trợ Chuyển đổi số & VNeID cho người cao tuổi',
    description: 'Đề nghị Đội thanh niên xung kích cấp xã mở điểm hỗ trợ người già hướng dẫn kích hoạt tài khoản định danh điện tử.',
    address: 'Nhà văn hóa thôn Chiến Chiện, xã Thanh Oai',
    category: 'youth_field',
    targetOrganization: 'youth',
    status: 'processing',
    departmentAssigned: 'Đoàn TNCS Hồ Chí Minh Xã (Khối MTTQ)',
    imageUrl: 'https://picsum.photos/seed/2/300/200',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    timeAgo: '3 phút trước',
    likes: 85,
    comments: 19,
    ubndResponse: {
      officerName: 'Đồng chí Lê Hoàng Nam (Bí thư Đoàn Xã)',
      department: 'BTV Đoàn Thanh niên Xã Thanh Oai',
      officialContent: 'Đoàn Xã đã thành lập 5 Đội Tình nguyện Chuyển đổi số trực tại các Nhà văn hóa thôn vào thứ 7 và Chủ nhật hàng tuần.',
      documentNumber: 'Số 18/KH-ĐTN',
      responseDate: '25/07/2026 09:00',
    },
  },
  {
    id: '3',
    title: 'Đề xuất Hội Phụ nữ nhân rộng mô hình "Gia đình 5 không 3 sạch"',
    description: 'Đề nghị Hội Phụ nữ xã tập huấn phân loại rác thải tại nguồn và tặng thùng rác thân thiện môi trường cho hội viên.',
    address: 'Xóm 4, xã Thanh Oai, Hà Nội',
    category: 'women_field',
    targetOrganization: 'women',
    status: 'pending',
    departmentAssigned: 'Hội Liên hiệp Phụ nữ Xã (Khối MTTQ)',
    imageUrl: 'https://picsum.photos/seed/3/300/200',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    timeAgo: '5 phút trước',
    likes: 31,
    comments: 4,
  },
  {
    id: '4',
    title: 'Hội Cựu chiến binh tuần tra nhân dân và giữ gìn an ninh trật tự đêm',
    description: 'Phản ánh tiếng ồn homestay và loa kéo qua 23h đêm gây ảnh hưởng giấc ngủ của bà con nhân dân.',
    address: 'Số 06 thôn 3, xã Ba Vì, Hà Nội',
    category: 'veterans_field',
    targetOrganization: 'veterans',
    status: 'done',
    departmentAssigned: 'Hội Cựu chiến binh Xã (Khối MTTQ)',
    imageUrl: 'https://picsum.photos/seed/4/300/200',
    createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    timeAgo: '6 phút trước',
    likes: 18,
    comments: 3,
    satisfactionRating: 5,
    ubndResponse: {
      officerName: 'Đỗ Văn Cường (Chủ tịch Hội CCB Xã)',
      department: 'Hội Cựu chiến binh Xã',
      officialContent: 'Tổ tuần tra Hội CCB phối hợp cùng Công an Xã đã vận động chủ cơ sở cam kết không phát loa quá 22h00.',
      documentNumber: 'Số 15/BB-CCB',
      responseDate: '23/07/2026 00:30',
    },
  },
  {
    id: '5',
    title: 'Hội Nông dân hỗ trợ vay vốn mua máy gặt liên hợp & vật tư phân bón',
    description: 'Kiến nghị Ban chấp hành Hội Nông dân xã phối hợp Ngân hàng CSXH giải ngân gói vay ưu đãi sản xuất vụ Mùa.',
    address: 'Cánh đồng Thôn 1, xã Thanh Oai',
    category: 'farmer_field',
    targetOrganization: 'farmers',
    status: 'processing',
    departmentAssigned: 'Hội Nông dân Xã (Khối MTTQ)',
    imageUrl: 'https://picsum.photos/seed/5/300/200',
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    timeAgo: '7 phút trước',
    likes: 89,
    comments: 23,
    ubndResponse: {
      officerName: 'Phạm Văn Hùng (Chủ tịch Hội Nông dân Xã)',
      department: 'Hội Nông dân Xã',
      officialContent: 'Hội Nông dân Xã đã lập danh sách 35 hộ vay vốn trình NHCSXH huyện duyệt giải ngân trong đợt 1.',
      documentNumber: 'Số 22/TB-HND',
      responseDate: '24/07/2026 15:20',
    },
  },
  {
    id: '6',
    title: 'Công đoàn cơ quan tư vấn bảo vệ quyền lợi người lao động',
    description: 'Hỗ trợ pháp lý về Hợp đồng lao động và chế độ BHXH cho công nhân các xưởng sản xuất địa phương.',
    address: 'Cụm công nghiệp làng nghề Thanh Oai',
    category: 'union_field',
    targetOrganization: 'union',
    status: 'processing',
    departmentAssigned: 'Công đoàn Xã (Khối MTTQ)',
    imageUrl: 'https://picsum.photos/seed/6/300/200',
    createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    timeAgo: '9 phút trước',
    likes: 45,
    comments: 18,
    ubndResponse: {
      officerName: 'Trịnh Thị Mai (Chủ tịch Công đoàn)',
      department: 'Công đoàn Xã Thanh Oai',
      officialContent: 'Công đoàn Xã đã tổ chức buổi tư vấn pháp luật lao động miễn phí cho 120 đoàn viên công đoàn.',
      documentNumber: 'Số 11/TB-CĐ',
      responseDate: '23/07/2026 08:20',
    },
  },
];
