import { FieldReport } from '../../types';

export const mockFieldReports: FieldReport[] = [
  {
    id: '1',
    title: 'Nắp cống hỏng gây nguy hiểm',
    description: 'Nắp cống bị hỏng gãy nứt gây mất an toàn giao thông cho người đi đường và trẻ em sinh sống tại khu vực.',
    address: 'Khu đất Dịch vụ 25,2ha Vân Canh, Hoài Đức, Hà Nội',
    category: 'security',
    status: 'processing',
    departmentAssigned: 'Bộ phận Địa chính - Xây dựng & Đô thị UBND Xã',
    imageUrl: 'https://picsum.photos/seed/1/300/200',
    createdAt: new Date(Date.now() - 1 * 60 * 1000).toISOString(),
    timeAgo: '1 phút trước',
    likes: 15,
    comments: 4,
    ubndResponse: {
      officerName: 'Nguyễn Văn Minh',
      department: 'Bộ phận Địa chính - Xây dựng & Đô thị UBND Xã',
      officialContent: 'UBND Xã đã cử Cán bộ Địa chính xuống kiểm tra thực địa. Đã lập biên bản ghi nhận và thông báo cho đơn vị thi công đúc nắp đan bê tông thay thế trong ngày 24/07.',
      documentNumber: 'Số 89/TB-UBND',
      responseDate: '23/07/2026 10:15',
    },
  },
  {
    id: '2',
    title: 'Cống tắc khu đất dịch vụ gây ngập',
    description: 'Tuyến cống thoát nước đường 24m bị ứ đọng rác và bùn thải gây ngập úng nhẹ khi trời mưa lớn.',
    address: 'Đường 24m khu đất dịch vụ, Hoài Đức, Hà Nội',
    category: 'environment',
    status: 'processing',
    departmentAssigned: 'Bộ phận Môi trường & Hạ tầng UBND Xã',
    imageUrl: 'https://picsum.photos/seed/2/300/200',
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    timeAgo: '3 phút trước',
    likes: 22,
    comments: 6,
    ubndResponse: {
      officerName: 'Trần Thị Thu Hương',
      department: 'Bộ phận Môi trường & Hạ tầng UBND Xã',
      officialContent: 'Cán bộ Xã đã phối hợp với Công ty Môi trường Đô thị triển khai xe nạo vét bùn cống. Dự kiến hoàn thành nạo vét toàn tuyến trước 17h00 hôm nay.',
      documentNumber: 'Số 91/CV-UBND',
      responseDate: '23/07/2026 09:30',
    },
  },
  {
    id: '3',
    title: 'Đề nghị UBND xã xử lý bãi rác tự phát',
    description: 'Khu vực sát đường giao thông hình thành bãi rác tự phát gây mất vệ sinh môi trường và mỹ quan bãi sông.',
    address: 'Khu vực Chiến Chiện, xã Thanh Oai, Hà Nội',
    category: 'environment',
    status: 'done',
    departmentAssigned: 'Bộ phận Tài nguyên Môi trường UBND Xã',
    imageUrl: 'https://picsum.photos/seed/3/300/200',
    createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    timeAgo: '5 phút trước',
    likes: 54,
    comments: 12,
    satisfactionRating: 5,
    ubndResponse: {
      officerName: 'Lê Hoàng Nam (Phó Chủ tịch UBND Xã)',
      department: 'UBND Xã Thanh Oai',
      officialContent: 'UBND Xã đã huy động lực lượng Đoàn thanh niên và xe hốt rác chuyên dụng giải tỏa hoàn toàn bãi rác tự phát. Đồng thời đã lắp biển Cấm đổ rác và camera giám sát tại khu vực.',
      documentNumber: 'Số 102/BC-UBND',
      responseDate: '22/07/2026 16:45',
      resultImageUrl: 'https://picsum.photos/seed/30/300/200',
    },
  },
  {
    id: '4',
    title: 'Tiếng ồn từ homestay phát loa đêm',
    description: 'Khu vực homestay hát hò qua loa kéo quá 23h đêm gây ảnh hưởng giấc ngủ của bà con nhân dân.',
    address: 'Số 06 thôn 3, xã Ba Vì, Hà Nội',
    category: 'security',
    status: 'done',
    departmentAssigned: 'Công an Xã Ba Vì',
    imageUrl: 'https://picsum.photos/seed/4/300/200',
    createdAt: new Date(Date.now() - 6 * 60 * 1000).toISOString(),
    timeAgo: '6 phút trước',
    likes: 18,
    comments: 3,
    satisfactionRating: 5,
    ubndResponse: {
      officerName: 'Đại úy Phạm Văn Thắng',
      department: 'Công an Xã Ba Vì',
      officialContent: 'Công an Xã đã cử tổ công tác xuống nhắc nhở, yêu cầu chủ cơ sở homestay tắt loa và ký cam kết chấp hành nghiêm quy định về trật tự công cộng.',
      documentNumber: 'Số 15/BB-CAX',
      responseDate: '23/07/2026 00:30',
    },
  },
  {
    id: '5',
    title: 'Nhậu nhẹt mở loa đến 24h gây mất trật tự',
    description: 'Số 1 BT1 bắc linh đàm nhậu nhẹt hát hò quá giờ quy định.',
    address: 'Số 1 BT1 Bắc Linh Đàm, Phường Hoàng Liệt',
    category: 'security',
    status: 'pending',
    departmentAssigned: 'Bộ phận Văn hóa - Xã hội UBND Phường',
    imageUrl: 'https://picsum.photos/seed/5/300/200',
    createdAt: new Date(Date.now() - 7 * 60 * 1000).toISOString(),
    timeAgo: '7 phút trước',
    likes: 89,
    comments: 23,
  },
  {
    id: '6',
    title: 'Lấn chiếm lòng đường làm nơi vật liệu',
    description: 'Số nhà 68 đường DX4 tập kết cát đá lấn chiếm hết lối đi của người dân.',
    address: 'Số nhà 68 đường DX4, Khu đô thị Đặng Xá',
    category: 'construction',
    status: 'processing',
    departmentAssigned: 'Tổ Trật tự Đô thị UBND Xã',
    imageUrl: 'https://picsum.photos/seed/6/300/200',
    createdAt: new Date(Date.now() - 9 * 60 * 1000).toISOString(),
    timeAgo: '9 phút trước',
    likes: 45,
    comments: 18,
    ubndResponse: {
      officerName: 'Vũ Đức Anh',
      department: 'Tổ Trật tự Đô thị UBND Xã',
      officialContent: 'Tổ công tác đã ra văn bản thông báo yêu cầu hộ gia đình di dời vật liệu xây dựng trong 24 giờ. Nếu quá hạn sẽ tiến hành xử phạt vi phạm hành chính.',
      documentNumber: 'Số 44/TB-TTĐT',
      responseDate: '23/07/2026 08:20',
    },
  },
];
